spring:
  application:
    name: user-center-backend
  #Data source config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: ZJJ201225zjj
server:
  port: 8080
  # in front add /api prefix
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # field name of logic delete
      logic-delete-value: 1 # already deleted, default 1
      logic-not-delete-value: 0 # not delete, default 0


